# StaffWeapon by sord1d
# The weapon's strength can be adjusted in-game with /sw setfast || /sw setcharged
# However, feel free to change stuff down below anyway


# Do you want the plugin to check for updates?
# [true / false]
updatecheck: true

# fast shot
fast: 5

# charged shot
charged: 15

#Mob charged shot
mob: 5

#Down below are the spawn points. If you delete one manually, be sure to adjust the number of spawn points above.
#Number of spawn points | DO NOT CHANGE THIS UNLESS YOU DELETE A POINT MANUALLY! Use /sw addspawner to add a spawner.
total: 0

