name: CNStaffWeapon
version: '${project.version}'
main: eu.sordiddev.staffweapon.Staffweapon
api-version: 1.18
authors: [ sord1d ]
description: Staff weapon mod
website: gihub.com/sord1d
commands:
  sw:
    description: display info and help
permissions:
  staffweapon.get:
    description: permission to use /swget
  staffweapon.shoot.fast:
    description: permission to shoot the weapon (left klick)
  staffweapon.shoot.charge:
    description: permission to shoot the weapon (right click)
  staffweapon.admin:
    description: full permissions + show update info
  staffweapon.lookup:
    description: player can lookup damage dealt by weapon